### ISSUE TITLE
v2act: rhs explisit and implisit array assign not recognised

### ISSUE THREAD

**Issue by olerichter** [asyncvlsi/interact#4]
(let me know if you rather want the clear cut act issues in the act repo)
# current behavior

assignment of arrays without rage, implicitly assume the full range does not work:

```
module blk0(e0, out);
  input [4:0] e0;
  output [4:0] out;
  assign out = e0;
endmodule
```
with error message 
```
Assertion failed, file sync.cc, line 170
Assertion: lhs == NULL
ERR: no way
```

it also does not like the range description (not as important):
```
module blk0(e0, out);
  input [4:0] e0;
  output [4:0] out;
  assign out = e0[4:0];
endmodule
```

with error
```
Parse error: Expecting token `]', got `:'
	File `./expropt0_mapped.v', line: 5, col: 25
Exception: number=1, message -none-
FATAL: Uncaught exception
```

# proposed behavior

treat like:
```
module blk0(e0, out);
  input [4:0] e0;
  output [4:0] out;
  assign out = {e0[4],e0[3],e0[2],e0[1],e0[0]};
endmodule
```

or
```
module blk0(e0, out);
  input [4:0] e0;
  output [4:0] out;
  assign out[4]=e0[4];
  assign out[3]=e0[3];
  assign out[2]=e0[2];
  assign out[1]=e0[1];
  assign out[0]=e0[0];
endmodule
```
# why

yosis generates this notation (the first example)

**Comment by rmanohar** [comment]
Hm, I couldn't replicate the first error. I fixed the second one... can you send me the exact file that you were running + the library? I get this:

```
/* -- declarations -- */
defproc blk0 (bool? e0[5]; bool! out[5]);

defproc blk0 (bool? e0[5]; bool! out[5])
{
   /*--- types ---*/
   /*--- connections ---*/
   out=e0;
}
```
But a pass through like this will generate a type error. Is that the issue?

**Comment by olerichter** [comment]
yes you are correct in sync mode it works fine! 
i forgot to also write the option i executed with:
so the first error only with v2act -a

the type error caused by a pass trough i take care in a later step in the program, my plan is as an improvment after having a minimum working version to detect them and skip the synthesis of those

```
v2act -a -C syn::dualrail -l ../../lib/stdcells_qdi.act -n syn ./expropt0_mapped2.v
```

[expropt0_mapped.v.txt](https://github.com/asyncvlsi/interact/files/6230636/expropt0_mapped.v.txt)
[stdcells_qdi.act.txt](https://github.com/asyncvlsi/interact/files/6230640/stdcells_qdi.act.txt)

**Comment by rmanohar** [comment]
Ah okay. I pushed a fix.
